### ISSUE TITLE
Falsche Funktionsbezeichnung

### ISSUE THREAD

**Issue by n0j0games** [rhaschke/lecture#5]
https://github.com/rhaschke/lecture/blob/07b5757b80a2a3987b1bc344c5d37607f0524062/notebook/controller.py#L110

Es scheint mir so als müsste hier `c.position_control(c.im_server.target)` statt  `pose_control`  aufgerufen werden, da letzteres in `Controller()` nicht existiert.

**Comment by rhaschke** [comment]
Danke für den Hinweis.
